### ISSUE TITLE
stream-lines can "blow out of" the grid

### ISSUE THREAD

**Issue by logi** [rveciana/raster-streamlines#1]
If conditions are "just right" the (x,y) point being blown around by the (u,v) vectors can blow just outside the grid so so that indexing will fail.

After adding some debug code to `getValueAtPoint` an error occurs when:
```
x =  51.00132142654526
y = 135.99328626261288
```
and `uData.length==136`. This goes to the case where the distance from the top-left corner of the cell is nearly zero and attempts to set `u=uData[136][51]` but that's out of range. In the general case, where (x,y) is comfortably inside the cell, there is an explicit test on the indexing of `uData`.

I could make this problem go away locally by changing the tracing loop conditions to
```
  while(x >= 0 && x < this.uData[0].length-0.01 && y >= 0 && y < this.uData.length-0.01){
```
which stops the trace just as this situation might come up.

One could also argue that the loops should stop at length-1, i.e. not allow the point to move outside the grid at all and then a number of `if(this.uData[y0] && this.uData[y0][x0])` tests could be removed... and reading this now, the tracing ignores wind in points with zero horizontal wind since they will be falsy and the test fails.

**Comment by logi** [comment]
I'm planning to make a pull request tomorrow (or "soon") which at least fixes the loop boundaries. I could also make another one which replaces the weighted-average function in the current `getValueAtPoint` with a simpler and more robust bilinear interpolation.

The weighted-average method could be beneficial if the u,v arrays are sparse and there might be null or undefined values in there, but the current code only checks the u component, so that's not what's going on.

**Comment by rveciana** [comment]
Sure, any PR will be appreciated!

**Comment by logi** [comment]
After a bit of experimentation and testing with our wind plots, I keep running into new corner cases in `getValueAtPoint`. I'm now testing a version in our fork which uses bilinear interpolation instead (which magically becomes linear extrapolation if you go outside the grid). In theory you could trace a particle off to an arbitrary distance, or loop it back onto the grid, it would just be silly.

However, it doesn't produce _exactly_ the same streamlines as the weighted-average method. All the "simple" unit tests pass unchanged but the complex cases produce a slightly different number of lines. Looking at some images side-by-side, the results seem completely equivalent to me. Here is the included test image before and after the change (and making the coastline distinct from the streamlines):

Before:
![streamlines-before](https://user-images.githubusercontent.com/217723/95982116-045edc00-0e20-11eb-9469-2cdc3c312509.png)

After:
![streamlines](https://user-images.githubusercontent.com/217723/95982156-0fb20780-0e20-11eb-9bec-3dbf673c1c1d.png)

@rveciana Is it acceptable to change the output in this way in non-failing cases? Also, how do you feel about the use of `const` and other more modern javascript syntax in new code, as long as the transpiler knows what to do with it?
